PUT https://fitnes.iran.liara.run/api/moves/d200fef6-d67d-4eed-a8a3-4d83acface59 HTTP/1.1
Content-Type: application/json

{
    "name": "update"
}

### 

DELETE https://fitnes.iran.liara.run/api/moves/d200fef6-d67d-4eed-a8a3-4d83acface59 HTTP/1.1

###

# @name signin
POST https://fitnes.iran.liara.run/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "Fitness2023"
}

###

GET https://fitnes.iran.liara.run/api/categories HTTP/1.1
Authorization: {{jwt}}

###

GET https://fitnes.iran.liara.run/api/categories/dd6b9c5c-f1b3-4b10-9e4f-147845425ba3 HTTP/1.1
Authorization: {{jwt}}

###

POST https://fitnes.iran.liara.run/api/categories/dd6b9c5c-f1b3-4b10-9e4f-147845425ba3/moves HTTP/1.1
Authorization: {{jwt}}
Content-Type: application/json

{
    "name": "move name"
}

@jwt = {{signin.response.body.data.token}}