# @name signin
POST http://localhost:3000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "Fitness2023"
}

###

POST http://localhost:3000/api/plans HTTP/1.1
Authorization: {{jwt}}
Content-Type: application/json

{
    "name": "user 2",
    "description": "something",
    "startedAt": "2023-12-05",
    "sessions": [
        {
            "moves": [
                {
                    "name": "move-1",
                    "quantity": "2 x 5"
                },
                {
                    "name": "move-3",
                    "quantity": "5 x 2"
                }
            ]
        },
        {
            "moves": [
                {
                    "name": "move-3",
                    "quantity": "2 x 5"
                },
                {
                    "name": "move-4",
                    "quantity": "15 x 5"
                }
            ]
        }
    ]
}

###

GET http://localhost:3000/api/plans HTTP/1.1
Authorization: {{jwt}}

###

GET http://localhost:3000/api/plans/bbw76oct

###

@jwt = {{signin.response.body.data.token}}