GET https://fitnes.iran.liara.run/api/moves HTTP/1.1
Authorization: {{jwt}}

###

POST https://fitnes.iran.liara.run/api/moves HTTP/1.1
Content-Type: application/json

{
    "name": "Move 2"
}

###

PUT https://fitnes.iran.liara.run/api/moves/d200fef6-d67d-4eed-a8a3-4d83acface59 HTTP/1.1
Content-Type: application/json

{
    "name": "update"
}

### 

DELETE https://fitnes.iran.liara.run/api/moves/d200fef6-d67d-4eed-a8a3-4d83acface59 HTTP/1.1

###

# @name signin
POST https://fitnes.iran.liara.run/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "Fitness2023"
}

###

@jwt = {{signin.response.body.data.token}}